### ISSUE TITLE
More Insignia selection

### ISSUE THREAD

**Issue by Spooky-Nikki** [2bnb/2bnb-essentials#43]
Maybe add Pride Flags to the Insignia section.

**Comment by Saborknight** [comment]
Well, gib images and we gib insignias ;)

**Comment by Spooky-Nikki** [comment]
[Pride-Flags.zip](https://github.com/2bnb/2bnb-essentials/files/6665748/Pride-Flags.zip)
Gave images, gib insignias

**Comment by Saborknight** [comment]
Done in commit 9e0f7a75c8afeb4e7dd7aaf1505a4614b7417031
