### ISSUE TITLE
Create new vehicle inventory presets changer

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-essentials#44]
Create new presets interface to allow us to swap vehicle inventories between specific presets on the fly.

**Comment by tier22** [comment]
Would making a new vehicle that inherits from the existing one with a different inventory be considered "unnecessarily complex"? 
I see it this way: we have a basic HMMWV, from which we inherit HMMWV (Heavy AT) with Javelins/TOWs, HMMWV (Medical) with medical stuff and so on?

**Comment by Saborknight** [comment]
Depends on what the overhead is between the two methods. Testing is needed to ascertain which is faster and better to use in a multiplayer environment.
I didn't think of that as a possible method though, thanks for bringing it up!
