### ISSUE TITLE
[SUGGESTION/RETEXTURE] Replace a NOR-SOF platecarriers with a retextured CPC platecarrier from the CUP

### ISSUE THREAD

**Issue by tier22** [2bnb/2bnb-essentials#50]
Here is the example of the textures I made:
https://drive.google.com/file/d/1Icf8tn1iL7_bJeq4v1HA2YBAX8c6UMEY/view?usp=sharing

**Comment by Saborknight** [comment]
Not NORSOF anymore, but could still be used for German stuff too
